### ISSUE TITLE
[Mac] Dark mouse cursor is hard to see on dark background

### ISSUE THREAD

**Issue by flowmemo** [zeit/hyper#1045]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: OS X 10.11.6
- **Hyper.app version**: 0.8.3 (0.8.3.873)
- **The issue is reproducible in vanilla Hyper.app**: 

## Issue

Hyper is cool! But I find the default mouse cursor of OS X is hard to see on dark background, especially when the screen is full of text.

![screenshot](https://cloud.githubusercontent.com/assets/11701553/20638259/e370a812-b3dc-11e6-93d6-122b50e2d577.png)

System-provided terminal and iTerm2 use custom image of mouse cursor like this:
![d8e6e8a5d739406d33fc23d322e480cf-render](https://cloud.githubusercontent.com/assets/11701553/20638495/d788ad18-b3e3-11e6-9a04-7b89320ff23f.png)
(source: https://github.com/gnachman/iTerm2/blob/master/images/IBarCursor-huge.psd)

**Comment by flowmemo** [comment]
Some text editors like VS Code, Sublime Text have both white and black mouse cursor. They choose color against the  background color of theme.

A temporary workaround is adding the following css into `termCSS` , which replace the original  cursor with the white one in vscode.
``` css
 * { cursor: -webkit-image-set(url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAQAAAC1+jfqAAAAL0lEQVQoz2NgCD3x//9/BhBYBWdhgFVAiVW4JBFKGIa4AqD0//9D3pt4I4tAdAMAHTQ/j5Zom30AAAAASUVORK5CYII=') 1x, url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAQAAADZc7J/AAAAz0lEQVRIx2NgYGBY/R8I/vx5eelX3n82IJ9FxGf6tksvf/8FiTMQAcAGQMDvSwu09abffY8QYSAScNk45G198eX//yev73/4///701eh//kZSARckrNBRvz//+8+6ZohwCzjGNjdgQxkAg7B9WADeBjIBqtJCbhRA0YNoIkBSNmaPEMoNmA0FkYNoFKhapJ6FGyAH3nauaSmPfwI0v/3OukVi0CIZ+F25KrtYcx/CTIy0e+rC7R1Z4KMICVTQQ14feVXIbR695u14+Ir4gwAAD49E54wc1kWAAAAAElFTkSuQmCC') 2x) 5 8, text; }
```
(source: 
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/viewParts/lines/viewLines.css#L45
https://github.com/Microsoft/vscode/issues/754 )
