### ISSUE TITLE
Auto Switch Theme Dark Mode / Light Mode

### ISSUE THREAD

**Issue by chrisgrieser** [zeit/hyper#6305]
**Is your feature request related to a problem? Please describe.**
Most apps are able to automatically switch between a dark and a light theme based on the appearance of the OS. Especially since Hyper has somewhat of a focus on being "stylish", I am quite surprised that it isn't possible to somehow automatically switch between two themes.

**Describe the solution you'd like**
A configuration to switch between light and dark theme, best on the OS appearance.

**Describe alternatives you've considered**
- I looked for plugins, but it seems there is [only this one](https://www.npmjs.com/package/hyper-day-night-switch) which is not working properly (and not allowing theme choices, anyway.)
- I also considered scripting changes to the hyper config, but really, this should be doable in a nicer way.

**Comment by 5ouma** [comment]
I want this feature too!
I have tried on CSS with this, but it didn’t work well.
```css
@media (prefers-color-scheme: light/dark) {}
```

Is there anyone who knows how to specify background color, font color, cursor color, etc…
(They didn’t work with these because it didn’t change color all of windows.)
```css
.hyper_main {
    background: /* some color or CSS variable */;
    background-color: /* some color or CSS variable */;
    font-color: /* some color or CSS variable */;
}
```
If I could specify these, I finally make it possible to change color by system appearance.

However, it’s better to be able to configure with default setting so please make this possible.
